name: test
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - boilerplate
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: realworld
        ports:
          - 5432:5432
    steps:
      - uses: actions/setup-go@v4
        with:
          go-mod-file: go.mod

      - name: Check out code
        uses: actions/checkout@v3

      - name: Mod tidy
        run: go mod tidy

      - name: Test
        run: go test -v ./...